### ISSUE TITLE
TASK Add tag of the git submodule to the public release in github workflow

### ISSUE THREAD

**Issue by thejhh** [hangovergames/project-memory#85]
See the commented part. This could be changed to use the git submodule ref, since that should be the tag of the release on the public repository.

```
    - name: Create Public Release
      id: create_public_release
      ...
      with:
        owner: hangovergames
        repo: project-memory
#        tag_name: ${{ github.ref }}
      ...
```
